version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 9000:80
    volumes:
      #- "./landingpage/nginx-proxy.conf:/etc/nginx/conf.d/default.conf"
      - C:\data\coding\envirocar\auth-proxy\docker-nginx-proxy.conf:/etc/nginx/conf.d/default.conf
      #- ./docker-nginx-proxy.conf:/etc/nginx/conf.d/default.conf"
  auth-proxy:
    build:
      context: ./
      args:
        - VERSION=0.0.1-SNAPSHOT
    image: envirocar/auth-proxy
    ports:
      - 9999:9999
    environment:
      - AUTH_PROXY_CONTEXT_PATH=/auth-proxy
      - AUTH_PROXY_LOG_LEVEL=INFO