server:
  port: 9999
  servlet:
    session:
      cookie:
        max-age: PT30M
        
# The proxy endpoint
auth-proxy:
    target:
      uri: https://envirocar.org/api/stable/


#
# Logging configuration
debug: true
logging:
  file: target/auth-proxy.log
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework: DEBUG
