server:
  port: 9999
  servlet:
    context-path: ${AUTH_PROXY_CONTEXT_PATH:/}
    session:
      cookie:
        max-age: PT30M
        
# The proxy endpoint
auth-proxy:
    target:
      uri: https://envirocar.org/api/stable/


#
# Logging configuration
debug: false
logging:
  file: target/auth-proxy.log
  config: classpath:logback.xml
  level:
    root: ${AUTH_PROXY_LOG_LEVEL:INFO}
#    org.envirocar: DEBUG
#    org.springframework: DEBUG
