server:
  port: 9999
  servlet:
    session:
      cookie:
        max-age: PT30M

#server.servlet.context-path=/api

#
# The proxy endpoint
auth-proxy:
    target:
      uri: https://envirocar.org/api/stable/


#
# Logging configuration
debug: true
logging:
  config: classpath:logback.xml
  level:
    root: INFO
    org.springframework: INFO
